name: Shell commands

on: 
    push:
      branches:
        - master
        - 'feature/*' # es para features/algo
        - 'feature/**' # es para feature/feate/algo
        

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name:  echo a string 
        run: echo "Hello World"
      - name: multiline script
        run: | 
          node -v
          npm -v 

  create_commit:
    runs-on: ubuntu-latest 
    permissions:
      issues: write 
    steps:
    # git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY"
      - name: Push a random Files
        run: |
          pwd
          ls -a
          git init
          git remote set-url origin ${{ secrets.ssh }}
          git config --global user.email "my_bot@botmail.com"
          git config --global user.name "mybotname"
          git status
          ls -a
          echo "patita love" >> l.txt
          ls -a
          git add .
          git commit -m "pl"
          git fetch origin master
          git push origin HEAD:master

      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
            }' \
          --fail